// Exports

export const permissions: {name: string, description: string}[] = [
    {name: 'account.manage', description: 'Edit the account details'},
    {name: 'ticket.view', description: 'View the ticket details'},
    {name: 'ticket.create', description: 'Create new tickets'},
    {name: 'ticket.update', description: 'Update existing ticket details'},
    {name: 'ticket.delete', description: 'Delete existing tickets'},
    {name: 'team.view', description: 'View the team details'},
    {name: 'team.create', description: 'Create new teams'},
    {name: 'team.update', description: 'Update existing team details'},
    {name: 'team.delete', description: 'Delete existing teams'},
    {name: 'comment.view', description: 'View the comments on a ticket'},
    {name: 'comment.create', description: 'Create new comments on a ticket'},
    {name: 'comment.update', description: 'Update existing comment details'},
    {name: 'comment.delete', description: 'Delete existing comments'},
    {name: 'user.view', description: 'View the user details'},
    {name: 'user.create', description: 'Create new users'},
    {name: 'user.update', description: 'Update existing user details'},
    {name: 'user.delete', description: 'Delete existing users'},
    {name: 'performance.view', description: 'View the performance analytics'},
];

export const roles: {name: string, description: string}[] = [
    {name: 'owner', description: 'The owner of the account, can do anything'},
    {name: 'admin', description: 'The admin of the account, can do anything except manage the account'},
    {name: 'manager', description: 'The manager of the account, can manage the tickets, teams, comments and view the performance analytics'},
    {name: 'employee', description: 'The employee of the account, can view the tickets and comments and manage comments on tickets'},
]

export const rolePermissions: {roleName: string, permissionName: string}[] = [
    {roleName: 'owner', permissionName: 'account.manage'},
    {roleName: 'owner', permissionName: 'ticket.view'},
    {roleName: 'owner', permissionName: 'ticket.create'},
    {roleName: 'owner', permissionName: 'ticket.update'},
    {roleName: 'owner', permissionName: 'ticket.delete'},
    {roleName: 'owner', permissionName: 'team.view'},
    {roleName: 'owner', permissionName: 'team.create'},
    {roleName: 'owner', permissionName: 'team.update'},
    {roleName: 'owner', permissionName: 'team.delete'},
    {roleName: 'owner', permissionName: 'comment.view'},
    {roleName: 'owner', permissionName: 'comment.create'},
    {roleName: 'owner', permissionName: 'comment.update'},
    {roleName: 'owner', permissionName: 'comment.delete'},
    {roleName: 'owner', permissionName: 'user.view'},
    {roleName: 'owner', permissionName: 'user.create'},
    {roleName: 'owner', permissionName: 'user.update'},
    {roleName: 'owner', permissionName: 'user.delete'},
    {roleName: 'owner', permissionName: 'performance.view'},
    {roleName: 'admin', permissionName: 'ticket.view'},
    {roleName: 'admin', permissionName: 'ticket.create'},
    {roleName: 'admin', permissionName: 'ticket.update'},
    {roleName: 'admin', permissionName: 'ticket.delete'},
    {roleName: 'admin', permissionName: 'team.view'},
    {roleName: 'admin', permissionName: 'team.create'},
    {roleName: 'admin', permissionName: 'team.update'},
    {roleName: 'admin', permissionName: 'team.delete'},
    {roleName: 'admin', permissionName: 'comment.view'},
    {roleName: 'admin', permissionName: 'comment.create'},
    {roleName: 'admin', permissionName: 'comment.update'},
    {roleName: 'admin', permissionName: 'comment.delete'},
    {roleName: 'admin', permissionName: 'user.view'},
    {roleName: 'admin', permissionName: 'user.create'},
    {roleName: 'admin', permissionName: 'user.update'},
    {roleName: 'admin', permissionName: 'user.delete'},
    {roleName: 'admin', permissionName: 'performance.view'},
    {roleName: 'manager', permissionName: 'ticket.view'},
    {roleName: 'manager', permissionName: 'ticket.create'},
    {roleName: 'manager', permissionName: 'ticket.update'},
    {roleName: 'manager', permissionName: 'ticket.delete'},
    {roleName: 'manager', permissionName: 'team.view'},
    {roleName: 'manager', permissionName: 'team.create'},
    {roleName: 'manager', permissionName: 'team.update'},
    {roleName: 'manager', permissionName: 'team.delete'},
    {roleName: 'manager', permissionName: 'comment.view'},
    {roleName: 'manager', permissionName: 'comment.create'},
    {roleName: 'manager', permissionName: 'comment.update'},
    {roleName: 'manager', permissionName: 'comment.delete'},
    {roleName: 'manager', permissionName: 'performance.view'},
    {roleName: 'employee', permissionName: 'ticket.view'},
    {roleName: 'employee', permissionName: 'comment.view'},
    {roleName: 'employee', permissionName: 'comment.create'},
    {roleName: 'employee', permissionName: 'comment.update'},
    {roleName: 'employee', permissionName: 'comment.delete'},
];

